### ISSUE TITLE
[feature request] Can I draw text with outlines? 

### ISSUE THREAD

**Issue by arithxp** [iraizo/nvidia-overlay-hijack#4]
Hello sir.

Can I draw text with outlines?
Text without outlines is sometimes difficult to distinguish from the background.

**Comment by iraizo** [comment]
Please read the FAQ.

**Comment by arithxp** [comment]
> Please read the FAQ, this is only a base, anything else is open source on the internet to implement this is literally just D2D

okay. sorry. I'll add it myself.
